clear;
close all;

% Input: a pool of segments generated by the "region proposal" algorithm
% Output: each video is represented as a tree of tubes (spatial-temporal segments)
% and each tube is assigned a label via the data-driven clustering algorithm

addPathVar;

% Paste the segments into tubes (spatio-temporal segments) via clustering 
num_clusters = 20;
for i = 1 : length(videos)
  cluster_segments_per_video(vid, num_clusters);
end

% Learn the appearance models for the foreground segments. 
% Here we only use the color histogram feature.
for i = 1 : length(videos)
  gen_bg_segments(i);
end
train_fg_models;

% Prune, merge, and organize the tubes into a tree (for each video independently)
% The learnt appearance models are used to prune the tubes
hier_cluster_per_video

% compute the features (dense trajectory) for each tube
for i = 1 : length(videos)
  compute_tube_feature(i);
end

% Assign labels to the tubes via data-driven clustering
cluster_tube_iterative;

% Rather than feed raw features into the structured model, we use the
% pretrained scores
pretrain_root_feature;
train_test_setup;
